---
Standards:
  -
    Title: Styles And Presentation
    Description: "Intro to CSS, CSS Walk-through, Classes and IDs, Units, Problem Set: Book Review Site"
    UID: b977acaff4fff984306b10fc63996e2a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: f04438de0c2a14673944635779a90a66
        Path: /styles-and-presentation/intro-to-css.md
      -
        Type: Lesson
        UID: 948309edcd1bd5a21b41aaa1624e4f56
        Path: /styles-and-presentation/css-walk-through.md
      -
        Type: Lesson
        UID: f7def17150f588c4f73cc5c32f0f4ac9
        Path: /styles-and-presentation/classes-and-ids.md
      -
        Type: Lesson
        UID: ff546c87e0d9d5c85219f847e689a996
        Path: /styles-and-presentation/units.md
      -
        Type: Lesson
        UID: 8d9e7bed804601f09191517e81507275
        Path: /styles-and-presentation/problem-set-book-review-site.md
