---
Standards:
  -
    Title: Web Browsers and Structuring Content
    Description: "Browsers and Dev Tools, The DOM and HTML, Intro to HTML, Content Elements, Sectioning Elements, Problem Set: Structuring Content"
    UID: 1d2da6520164121263e592310e0f6f48
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8d9d10ea9f5528b4727c59d30d59ff5f
        Path: /web-browsers/browsers-and-dev-tools.md
      -
        Type: Lesson
        UID: 4c26c8d2188464039fb99418a156376d
        Path: /web-browsers/the-dom-and-html.md
     -
       Type: Lesson
       UID: 3e59f2f7f1a3569bfe9098bddede7105
       Path: /structuring-content/intro-to-html.md
     -
       Type: Lesson
       UID: 417921f9b31aff200457e4dcd409671f
       Path: /structuring-content/content-elements.md
     -
       Type: Lesson
       UID: 6704a2ab7992bfb7baa303d21a81c448
       Path: /structuring-content/sectioning-elements.md
     -
       Type: Lesson
       UID: dce3c31202fea299477ce39769337328
       Path: /structuring-content/problem-set-structuring-content.md
  -
    Title: Styles And Presentation
    Description: "Intro to CSS, CSS Walk-through, Classes and IDs, Problem Set: Book Review Site"
    UID: b977acaff4fff984306b10fc63996e2a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: f04438de0c2a14673944635779a90a66
        Path: /styles-and-presentation/intro-to-css.md
      -
        Type: Lesson
        UID: 948309edcd1bd5a21b41aaa1624e4f56
        Path: /styles-and-presentation/css-walk-through.md
      -
        Type: Lesson
        UID: f7def17150f588c4f73cc5c32f0f4ac9
        Path: /styles-and-presentation/classes-and-ids.md
      -
        Type: Lesson
        UID: 8d9e7bed804601f09191517e81507275
        Path: /styles-and-presentation/problem-set-book-review-site.md
  -
    Title: More Neat CSS Things
    Description: "Cascade & Inheritance, More Selectors, Problem Set: More Neat CSS Things, Activity: Group Selector Fun"
    UID: ae429788a99c039bd77d9d2cf648e352
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: adcdf467194e0b8312fdce1bd8862f54
        Path: /more-neat-css-things/cascade-inheritance.md
      -
        Type: Lesson
        UID: 703080637d3b387dc87ef3e98065d105
        Path: /more-neat-css-things/more-selectors.md
      -
        Type: Lesson
        UID: 4c7e71500b7afe53862df291daf6255c
        Path: /more-neat-css-things/problem-set-more-neat-css-things.md
      -
        Type: Instructor
        UID: 77a387f9
        Path: /more-neat-css-things/activity-group-selector-fun.instructor.md
      -
        Type: Lesson
        UID: c4ad833159bae79a445d1f742822b1f2
        Path: /more-neat-css-things/activity-group-selector-fun.md
  -
    Title: Layout
    Description: "Box Model, Units, The Display Property, Intro to Flexbox, Layout with CSS Grid, Problem Set: Layout"
    UID: ebd9bec4d70abc789d439c1f136b0538
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a5c8dbda7a59bd89f8f9cbae03965144
        Path: /layout/box-model.md
      -
        Type: Lesson
        UID: ff546c87e0d9d5c85219f847e689a996
        Path: /layout/units.md
      -
        Type: Lesson
        UID: 875feea801032ad55884c0062a1b52cc
        Path: /layout/the-display-property.md
      -
        Type: Lesson
        UID: 34be75e924e8b69bf9044bd465bcffa3
        Path: /layout/intro-to-flexbox.md
      -
        Type: Lesson
        UID: 048145c61152e1c3754129f2ef24dd95
        Path: /layout/layout-with-css-grid.md
      -
        Type: Lesson
        UID: e3e0334d5b0354d5be0af200c4893a85
        Path: /layout/problem-set-layout.md
  -
    Title: Learning Another Language
    Description: "Our Path; Hello, World!; FizzBuzz; Summary, Resources, and Next Steps; Semicolons; Variables; Objects; Intro to Functions; Additional Topics; Problem Set: Intro to JavaScript"
    UID: 9199ff6adef8940bbdbaa1cc4649bd9b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: b64f715461d8ea07a5090b0e6c6fe4bd
        Path: /learning-another-language/our-path.md
      -
        Type: Lesson
        UID: 347e2fc9fd53b23e7ec4e9f298559a3b
        Path: /learning-another-language/hello-world.md
      -
        Type: Lesson
        UID: bf20e1a2d48ddf361ead9e1c8c1b7b57
        Path: /learning-another-language/fizzbuzz.md
      -
        Type: Lesson
        UID: 474d0d30c7e2b733185f146af5802eaa
        Path: /learning-another-language/summary-resources-and-next-steps.md
      -
        Type: Lesson
        UID: 913f60b4dd20c2aa0b1115227ad4d405
        Path: /learning-another-language/semicolons.md
      -
        Type: Lesson
        UID: a1aeec36cd644da97ab126357e012e1f
        Path: /learning-another-language/variables.md
      -
        Type: Lesson
        UID: eeab53fc59a3dc582cd8580253fb9827
        Path: /learning-another-language/objects.md
      -
        Type: Lesson
        UID: 659c7240cc40695d5e429e5c36386fa3
        Path: /learning-another-language/intro-to-functions.md
      -
        Type: Lesson
        UID: 71c286a7-12b3-48e3-9e19-816ff8f2d9d4
        Path: /learning-another-language/vscode-and-style.md
      -
        Type: Lesson
        UID: cfd5f597d9a76eaf406cb4125063e0fb
        Path: /learning-another-language/additional-topics.md
      -
        Type: Lesson
        UID: 36e4d945
        Path: /learning-another-language/problem-set-intro-to-javascript.md
      -
        Type: Lesson
        UID: f29ce62d-1fa4-4e88-93af-fb751e2dbb6d
        Path: /learning-another-language/activity-exploring-javascript.md
  -
    Title: Functions
    Description: "Arrow Functions, Callback Functions, Anonymous Functions, Problem Set: Functions"
    UID: e93acb146e114b5dfa6ce2d12dcb96e4
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 0ce48336e54c50096561ef112a43998b
        Path: /functions/arrow-functions.md
      -
        Type: Lesson
        UID: 0bcb2dc513467f0ef65a6bba6635c1ea
        Path: /functions/callback-functions.md
      -
        Type: Lesson
        UID: 290fdf2cff17807ea8b5bb0a8e5f6880
        Path: /functions/anonymous-functions.md
      -
        Type: Instructor
        UID: ca55dc98
        Path: /functions/problem-set-functions.instructor.md
      -
        Type: Lesson
        UID: 22bfb1a1
        Path: /functions/problem-set-functions.md
  -
    Title: Tests
    Description: "Reading Tests, Test Syntax Detail, Problem Set: Tests"
    UID: 2d8092a5
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a40cb618a5471bef09a22c78348b4547
        Path: /tests/reading-tests.md
      -
        Type: Lesson
        UID: 0811cf72e5bfff1f4cfd1357972481aa
        Path: /tests/test-syntax-detail.md
      -
        Type: Lesson
        UID: 1d5ceb96
        Path: /tests/problem-set-tests.md
  -
    Title: "Problem Set: Tool Library"
    Description: "Practice with Functions, Research OOP"
    UID: 46d7ee8a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: bbd59159
        Path: /problem-set-tool-library/tool-library.instructor.md
      -
        Type: Lesson
        UID: 80f0a0cd
        Path: /problem-set-tool-library/problem-set-tool-library.md
      -
        Type: Lesson
        UID: aae0de8d
        Path: /problem-set-tool-library/problem-set-tool-library-wave-2.md
  -
    Title: "Algorithmic Strategies"
    Description: "Divide and Conquer, Dynamic Programming, Problem Set: Algorithmic Strategies"
    UID: b1ec8907
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 282c6bfa
        Path: /algorithmic-strategies/algorithmic-strategies.instructor.md
      -
        Type: Lesson
        UID: 31eb5440
        Path: /algorithmic-strategies/divide-and-conquer.md
      -
        Type: Lesson
        UID: a9083082
        Path: /algorithmic-strategies/dynamic-programming.md
      -
        Type: Lesson
        UID: 673f70af
        Path: /algorithmic-strategies/problem-set-algorithmic-strategies.md
  -
    Title: Adding Behavior
    Description: "Connecting HTML, CSS, and JS; Changing the DOM"
    UID: a0d8555c7bb2bc809c15b9fc37560a5e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 11fc027a59fe1963ba5dc88c3c30e4fd
        Path: /adding-behavior/connecting-html-css-and-js.md
      -
        Type: Lesson
        UID: 206e76c0851277903fb91d8fca4e362f
        Path: /adding-behavior/changing-the-dom.md
  -
    Title: Event Handling
    Description: "Intro to Event Handling, Adding onclick Handling, Foreshadowing: State, Problem Set: Event Handling"
    UID: b7a2c117790fd3d9347e2dc80519e151
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 361b4130f4c5ab73de1043e514a8ee48
        Path: /event-handling/intro-to-event-handling.md
      -
        Type: Lesson
        UID: 4662421b1d590d31cd374fbdb3d14244
        Path: /event-handling/adding-onclick-handling.md
      -
        Type: Lesson
        UID: 97a3ad9ab680dbbe2254f61c3964e07d
        Path: /event-handling/foreshadowing-state.md
      -
        Type: Lesson
        UID: 1c7326a3cfb0353b88713902f959584b
        Path: /event-handling/problem-set-event-handling.md
  -
    Title: Calling APIs
    Description: "Intro to Asynchronous Programming, GET Requests With axios, POST Requests With axios, Managing Asynchronous Calls, Problem Set: Requests With JS"
    UID: ea98d11e0ad2c8fb97cba4671894b5be
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: df9579446a05c089f2c4925072f798e5
        Path: /calling-apis/calling-apis.instructor.md
      -
        Type: Lesson
        UID: 56ec483c4a41f36b614af17f1860c5ed
        Path: /calling-apis/intro-to-asynchronous-programming.md
      -
        Type: Lesson
        UID: d3a9923ac36a2dcc00b6a38839a9b361
        Path: /calling-apis/get-requests-with-axios.md
      -
        Type: Lesson
        UID: f66ca97c89f806852275a887be52e2e3
        Path: /calling-apis/post-requests-with-axios.md
      -
        Type: Lesson
        UID: 74275257eea05874614158a544388760
        Path: /calling-apis/managing-asynchronous-calls.md
      -
        Type: Instructor
        UID: 877cdfdd
        Path: /calling-apis/problem-set-requests-with-js.instructor.md
      -
        Type: Lesson
        UID: af9932f5
        Path: /calling-apis/problem-set-requests-with-js.md
  -
    Title: React Components
    Description: "Intro to React JS; Hello, World!; JSX; Components; Styling Components; Problem Set: Recreating Components"
    UID: 2b07c4b3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 536fdd9e
        Path: /react-components/react-components.instructor.md
      -
        Type: Lesson
        UID: 2a9c8e05
        Path: /react-components/intro-to-react-js.md
      -
        Type: Lesson
        UID: 5991512b
        Path: /react-components/hello-world.md
      -
        Type: Lesson
        UID: a931c8b5
        Path: /react-components/jsx.md
      -
        Type: Lesson
        UID: bb4d023f
        Path: /react-components/components.md
      -
        Type: Lesson
        UID: 794e8d8d
        Path: /react-components/styling-components.md
      -
        Type: Lesson
        UID: 29fee3f1
        Path: /react-components/problem-set-recreating-components.md
  -
    Title: Props
    Description: "Nested Components, props, PropTypes, Problem Set: Timeline"
    UID: c101520f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: f51978eb
        Path: /props/nested-components.md
      -
        Type: Lesson
        UID: 230f7e72
        Path: /props/props.md
      -
        Type: Lesson
        UID: b64be794
        Path: /props/proptypes.md
      -
        Type: Checkpoint
        UID: 235188b7
        Path: /props/problem-set-timeline.checkpoint.md
  -
    Title: State and Event Handling
    Description: "Event Handling, Using State, Updating State, Problem Set: Recreate Weather Report"
    UID: d4db3705
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: a9ce35e1
        Path: /state-and-event-handling/state-and-event-handling.instructor.md
      -
        Type: Lesson
        UID: 127fbd6b
        Path: /state-and-event-handling/event-handling.md
      -
        Type: Lesson
        UID: 62b88196
        Path: /state-and-event-handling/using-state.md
      -
        Type: Lesson
        UID: 78e21e09
        Path: /state-and-event-handling/updating-state.md
      -
        Type: Lesson
        UID: 1da518bb
        Path: /state-and-event-handling/problem-set-recreate-weather-report.md
  -
    Title: Lifting State Up
    Description: "Inspecting React State, Single Source of Truth, Passing Down Event Handlers, Lifting State Up, Problem Set: Lifting State Up"
    UID: ddc232ea
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 09de9b49
        Path: /lifting-state-up/inspecting-react-state.md
      -
        Type: Lesson
        UID: 32852ddd
        Path: /lifting-state-up/single-source-of-truth.md
      -
        Type: Lesson
        UID: 589f187c
        Path: /lifting-state-up/passing-down-event-handlers.md
      -
        Type: Lesson
        UID: 82f81bda
        Path: /lifting-state-up/lifting-state-up.md
      -
        Type: Lesson
        UID: abc286b1
        Path: /lifting-state-up/problem-set-lifting-state-up.md
  -
    Title: useEffect and Calling APIs
    Description: "useEffect After Render, Calling APIs from Components"
    UID: b778886a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 645ec05b
        Path: /useeffect-and-calling-apis/useeffect-after-render.md
      -
        Type: Lesson
        UID: dade3f84
        Path: /useeffect-and-calling-apis/calling-apis-from-components.md
  -
    Title: Handling Forms
    Description: "Controlled Forms, Submitting Forms, Problem Set: Forms and APIs"
    UID: c5e86e7e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: a939ecdf
        Path: /handling-forms/controlled-forms.instructor.md
      -
        Type: Lesson
        UID: e292aa10
        Path: /handling-forms/controlled-forms.md
      -
        Type: Lesson
        UID: c073ec6c
        Path: /handling-forms/submitting-forms.md
      -
        Type: Lesson
        UID: 2f5670a2
        Path: /handling-forms/problem-set-forms-and-apis.md
  -
    Title: Unit Wrap Up
    Description: "Activity: Mind Map"
    UID: 6efdc648
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cb7e8aab
        Path: /unit-wrap-up/activity-mind-map.md
