Standards:
  -
    Title: Web Browsers
    Description: Web Browsers
    UID: 1d2da6520164121263e592310e0f6f48
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8d9d10ea9f5528b4727c59d30d59ff5f
        Path: /web-browsers/dev-tools.md
      -
        Type: Lesson
        UID: 4c26c8d2188464039fb99418a156376d
        Path: /web-browsers/vision-accessibility.md
  -
    Title: Structuring Content
    Description: Structuring Content
    UID: 088327313237aac6e3715078d3f979a0
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 417921f9b31aff200457e4dcd409671f
        Path: /structuring-content/content-elements.md
      -
        Type: Lesson
        UID: 3e59f2f7f1a3569bfe9098bddede7105
        Path: /structuring-content/intro-to-html.md
      -
        Type: Lesson
        UID: e18a67eea39b0a77bf4555916f29b7b0
        Path: /structuring-content/old.md
      -
        Type: Lesson
        UID: dce3c31202fea299477ce39769337328
        Path: /structuring-content/problem-set-structuring-content.md
      -
        Type: Lesson
        UID: 6704a2ab7992bfb7baa303d21a81c448
        Path: /structuring-content/sectioning-elements.md
  -
    Title: Styles And Presentation
    Description: Styles And Presentation
    UID: b977acaff4fff984306b10fc63996e2a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: d8a3580f14007e6ec42d8c7ef04e157f
        Path: /styles-and-presentation/attributes-classes-and-ids.md
      -
        Type: Lesson
        UID: f04438de0c2a14673944635779a90a66
        Path: /styles-and-presentation/intro-to-css.md
  -
    Title: More Neat Css Things
    Description: More Neat Css Things
    UID: ae429788a99c039bd77d9d2cf648e352
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: adcdf467194e0b8312fdce1bd8862f54
        Path: /more-neat-css-things/cascade-inheritance.md
  -
    Title: Layout
    Description: Layout
    UID: ebd9bec4d70abc789d439c1f136b0538
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a5c8dbda7a59bd89f8f9cbae03965144
        Path: /layout/box-model.md
      -
        Type: Lesson
        UID: 32a8f7c7a619790eedd8b786088f765c
        Path: /layout/intro-to-css-grid.md
      -
        Type: Lesson
        UID: 34be75e924e8b69bf9044bd465bcffa3
        Path: /layout/intro-to-flexbox.md
