---
Standards:
  -
    Title: "Algorithmic Strategies"
    Description: "Divide & Conquer, Dynamic Programming"
    UID: b1ec8907
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 31eb5440
        Path: /algorithmic-strategies/divide-and-conquer.md
      -
        Type: Lesson
        UID: a9083082
        Path: /algorithmic-strategies/dynamic-programming.md
