Standards:
  -
    Title: Web Browsers
    Description: "Browsers and Dev Tools, The DOM and HTML"
    UID: 1d2da6520164121263e592310e0f6f48
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8d9d10ea9f5528b4727c59d30d59ff5f
        Path: /web-browsers/browsers-and-dev-tools.md
      -
        Type: Lesson
        UID: 4c26c8d2188464039fb99418a156376d
        Path: /web-browsers/the-dom-and-html.md
  -
    Title: Tests
    Description: "Problem Set: Tests"
    UID: 2d8092a5
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 1d5ceb96
        Path: /tests/problem-set-tests.md