Standards:
  -
    Title: Calling APIs
    Description: "Intro to Asynchronous Programming, GET Requests With axios, POST Requests With axios, Managing Asynchronous Calls, Problem Set: Requests With JS"
    UID: ea98d11e0ad2c8fb97cba4671894b5be
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: df9579446a05c089f2c4925072f798e5
        Path: /calling-apis/calling-apis.instructor.md
      -
        Type: Lesson
        UID: 56ec483c4a41f36b614af17f1860c5ed
        Path: /calling-apis/intro-to-asynchronous-programming.md
      -
        Type: Lesson
        UID: d3a9923ac36a2dcc00b6a38839a9b361
        Path: /calling-apis/get-requests-with-axios.md
      -
        Type: Lesson
        UID: f66ca97c89f806852275a887be52e2e3
        Path: /calling-apis/post-requests-with-axios.md
      -
        Type: Lesson
        UID: 74275257eea05874614158a544388760
        Path: /calling-apis/managing-asynchronous-calls.md
      -
        Type: Instructor
        UID: 877cdfdd
        Path: /calling-apis/problem-set-requests-with-js.instructor.md
      -
        Type: Lesson
        UID: af9932f5
        Path: /calling-apis/problem-set-requests-with-js.md
